import {
  addressFormValidator,
  portFormValidator,
  tagFormValidator,
} from "../../lib/builtin/commonFormValidators";
import { builtinComponentFactory } from "../../lib/builtin/componentFactory";
import { DataForm } from "../../lib/form/form";
import { GridGroup, GridItem } from "../../lib/form/gridUtils";
import { GFI } from "../../lib/formItem/formItem";
import type {
  FormItemNotify,
  ItemDescriptor,
} from "../../lib/formItem/formItemTypes";

type DeploymentField =
  | "deploymentId"
  | "serviceName"
  | "region"
  | "controlAddress"
  | "controlPort"
  | "publicAccess"
  | "workerCount"
  | "cpuPerWorker"
  | "memoryPerWorker"
  | "autoscaling"
  | "minWorkers"
  | "maxWorkers"
  | "retryEnabled"
  | "retryLimit"
  | "retryBackoff"
  | "secureTransport"
  | "certificateFingerprint"
  | "certificateBundle";

const integerRangeValidator = (
  min: number,
  max: number,
  label: string
): NonNullable<ItemDescriptor["validator"]> => {
  return (value: number) => {
    if (!Number.isInteger(value) || value < min || value > max) {
      return {
        severity: "error",
        message: `${label} must be an integer from ${min} to ${max}`,
      };
    }
  };
};

const serviceNameValidator: NonNullable<ItemDescriptor["validator"]> = (
  value: string
) => {
  if (!/^[a-z][a-z0-9-]{2,31}$/.test(value)) {
    return {
      severity: "error",
      message: "Use 3–32 lowercase letters, digits or hyphens",
    };
  }
};

const fingerprintValidator: NonNullable<ItemDescriptor["validator"]> = (
  value: string
) => {
  if (!/^[a-f\d]{40}$/i.test(value)) {
    return {
      severity: "error",
      message: "Expected a 40-character hexadecimal fingerprint",
    };
  }
};

const deploymentSchema: Record<DeploymentField, ItemDescriptor> = {
  deploymentId: {
    title: "Deployment ID",
    component: "input",
    required: true,
    disabled: true,
    hint: "Immutable identifier generated by the control plane",
    validator: tagFormValidator,
  },
  serviceName: {
    title: "Service name",
    component: "input",
    required: true,
    validator: serviceNameValidator,
    componentProps: {
      placeholder: "image-renderer",
      autoComplete: "off",
      maxLength: 32,
    },
  },
  region: {
    title: "Target region",
    component: "input",
    required: true,
    componentProps: {
      placeholder: "eu-central-1",
      autoComplete: "off",
    },
  },
  controlAddress: {
    title: "Controller address",
    component: "input",
    required: true,
    validator: addressFormValidator,
    hint: "Private IPv4 address of the deployment controller",
    componentProps: { placeholder: "10.24.0.12" },
  },
  controlPort: {
    title: "Controller port",
    component: "inputNum",
    required: true,
    validator: portFormValidator,
    componentProps: { min: 1, max: 65525 },
  },
  publicAccess: {
    title: "Public access",
    component: "checkbox",
    hint: "Expose the control endpoint outside the private network",
  },
  workerCount: {
    title: "Initial workers",
    component: "inputNum",
    required: true,
    validator: integerRangeValidator(1, 128, "Worker count"),
    componentProps: { min: 1, max: 128 },
  },
  cpuPerWorker: {
    title: "CPU per worker",
    component: "inputNum",
    required: true,
    validator: integerRangeValidator(1, 64, "CPU count"),
    hint: "Logical CPU cores reserved for each worker",
    componentProps: { min: 1, max: 64 },
  },
  memoryPerWorker: {
    title: "Memory, MiB",
    component: "inputNum",
    required: true,
    validator: integerRangeValidator(256, 262144, "Memory"),
    componentProps: { min: 256, max: 262144, step: 256 },
  },
  autoscaling: {
    title: "Autoscaling",
    component: "checkbox",
    hint: "Scale the worker pool according to pending jobs",
    onAfterChange: (_, enabled, mediator) => {
      mediator.setSchema((schema) => ({
        ...schema,
        minWorkers: {
          ...schema.minWorkers,
          disabled: !enabled,
          required: Boolean(enabled),
        },
        maxWorkers: {
          ...schema.maxWorkers,
          disabled: !enabled,
          required: Boolean(enabled),
        },
      }));
    },
  },
  minWorkers: {
    title: "Minimum workers",
    component: "inputNum",
    required: true,
    validator: integerRangeValidator(1, 128, "Minimum workers"),
    componentProps: { min: 1, max: 128 },
  },
  maxWorkers: {
    title: "Maximum workers",
    component: "inputNum",
    required: true,
    validator: integerRangeValidator(1, 512, "Maximum workers"),
    componentProps: { min: 1, max: 512 },
  },
  retryEnabled: {
    title: "Retry failed jobs",
    component: "checkbox",
    onAfterChange: (_, enabled, mediator) => {
      mediator.setSchema((schema) => ({
        ...schema,
        retryLimit: {
          ...schema.retryLimit,
          disabled: !enabled,
          required: Boolean(enabled),
        },
        retryBackoff: {
          ...schema.retryBackoff,
          disabled: !enabled,
          required: Boolean(enabled),
        },
      }));
    },
  },
  retryLimit: {
    title: "Retry limit",
    component: "inputNum",
    disabled: true,
    validator: integerRangeValidator(1, 20, "Retry limit"),
    componentProps: { min: 1, max: 20 },
  },
  retryBackoff: {
    title: "Backoff, ms",
    component: "inputNum",
    disabled: true,
    validator: integerRangeValidator(100, 60000, "Retry backoff"),
    componentProps: { min: 100, max: 60000, step: 100 },
  },
  secureTransport: {
    title: "Mutual TLS",
    component: "checkbox",
    hint: "Require authenticated and encrypted controller connections",
    onAfterChange: (_, enabled, mediator) => {
      mediator.setSchema((schema) => ({
        ...schema,
        certificateFingerprint: {
          ...schema.certificateFingerprint,
          disabled: !enabled,
        },
        certificateBundle: {
          ...schema.certificateBundle,
          disabled: !enabled,
        },
      }));
    },
  },
  certificateFingerprint: {
    title: "Certificate SHA-1",
    component: "input",
    validator: fingerprintValidator,
    componentProps: {
      placeholder: "40 hexadecimal characters",
      autoComplete: "off",
    },
  },
  certificateBundle: {
    title: "Certificate bundle",
    component: "file",
    hint: "Optional PEM bundle; a fingerprint or bundle is required",
    componentProps: { accept: ".pem,.crt,.cer" },
  },
};

export const PreviewApp = () => {
  return (
    <div
      style={{
        width: "1000px",
        margin: "16px auto",
        padding: 16,
        border: "1px solid rgba(255, 255, 255, 0.18)",
        borderRadius: 16,
        backgroundColor: "#040404",
        boxSizing: "border-box",
        overflowX: "auto",
      }}
    >
      <DataForm
        gridStyle={{ gridRow: "42px" }}
        componentFactory={builtinComponentFactory}
        confirmButtonProps={{ children: "Confirm and continue" }}
        schema={deploymentSchema}
        initialData={{
          deploymentId: "orbital-control-prod-01",
          serviceName: "image-renderer",
          region: "eu-central-1",
          controlAddress: "10.24.0.12",
          controlPort: 7443,
          publicAccess: false,
          workerCount: 12,
          cpuPerWorker: 4,
          memoryPerWorker: 8192,
          autoscaling: true,
          minWorkers: 6,
          maxWorkers: 48,
          retryEnabled: false,
          retryLimit: 3,
          retryBackoff: 1500,
          secureTransport: true,
          certificateFingerprint: "97fcb74a7f44c0064a6e89c80d61e9d453c8e9af",
        }}
        customValidate={(data) => {
          const issues: FormItemNotify<DeploymentField>[] = [];

          if (
            data.autoscaling === true &&
            typeof data.minWorkers === "number" &&
            typeof data.maxWorkers === "number" &&
            data.minWorkers > data.maxWorkers
          ) {
            issues.push({
              fld: "maxWorkers",
              severity: "error",
              message: "Maximum workers must not be below the minimum",
            });
          }

          if (
            data.secureTransport === true &&
            !data.certificateFingerprint &&
            !data.certificateBundle
          ) {
            issues.push({
              fld: "certificateFingerprint",
              severity: "error",
              message: "Provide a certificate fingerprint or bundle",
            });
          }

          if (data.publicAccess === true && data.secureTransport !== true) {
            issues.push({
              fld: "publicAccess",
              severity: "warning",
              message: "Public deployments should use mutual TLS",
            });
          }

          if (
            typeof data.workerCount === "number" &&
            typeof data.memoryPerWorker === "number" &&
            data.workerCount * data.memoryPerWorker > 131072
          ) {
            issues.push({
              fld: "memoryPerWorker",
              severity: "info",
              message: "The initial pool reserves more than 128 GiB",
            });
          }

          return issues;
        }}
        onConfirm={(data) =>
          alert(`Deployment accepted:\n${JSON.stringify(data, null, 2)}`)
        }
      >
        <GridGroup header="Deployment identity">
          {GFI("deploymentId", { controlColSpan: 1 })}
          {GFI("serviceName", { controlColSpan: 1 })}
          <GridGroup split header="Placement and exposure">
            {GFI("region", { controlColSpan: 1 })}
            {GFI("publicAccess")}
          </GridGroup>
        </GridGroup>

        <GridItem />

        <GridGroup split header="Capacity policy">
          <GridGroup header="Resources in one compact row">
            {GFI("workerCount")}
            {GFI("cpuPerWorker")}
            {GFI("memoryPerWorker")}
          </GridGroup>

          <GridGroup header="Autoscaling">
            {GFI("autoscaling")}
            <GridGroup header="A deliberately narrow worker range">
              {GFI("minWorkers", { controlColSpan: 1 })}
              {GFI("maxWorkers", { controlColSpan: 1 })}
              <GridItem />
            </GridGroup>
          </GridGroup>
        </GridGroup>

        <GridGroup header="Connectivity and trust" split>
          <GridGroup header="Control endpoint">
            {GFI("controlAddress", { controlColSpan: 1 })}
            {GFI("controlPort", { controlColSpan: 1 })}
          </GridGroup>

          <GridGroup header="Transport security">
            {GFI("secureTransport")}
            {GFI("certificateFingerprint", {
              labelColSpan: 1,
              controlColSpan: 1,
            })}
            {GFI("certificateBundle", {
              labelColSpan: 1,
              controlColSpan: 1,
            })}
          </GridGroup>
        </GridGroup>
      </DataForm>
    </div>
  );
};
